backend:
  name: git-gateway
  branch: master

media_folder: /src/images
public_folder: /src/images

collections:
  - label: Workshops
    name: workshops
    folder: content/workshops
    media_folder: /static/img/uploads
    public_folder: /img/uploads
    create: true
    slug: index
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }

  - label: Pages
    name: pages
    files:
      - label: Index
        name: index
        file: content/pages/index.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Projects, name: projects, widget: list, fields: [{label: Project, name: project, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: string}, {label: Image, name: image, widget: Image}]}]}
      - label: About
        name: about
        file: content/pages/about.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Board Mambers, name: boardMembers, widget: list, fields: [{label: Board Member, name: boardMembers, widget: object, fields: [{label: Position title, name: positionTitle, widget: string}, {label: Name, name: name, widget: string}, {label: Image, name: image, widget: image}]}]}
      - label: Links
        name: links
        file: content/pages/links.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Links, name: links, widget: list, fields: [{label: Link, name: link, widget: object, fields: [{label: Link Text, name: linkText, widget: string}, {label: URL, name: url, widget: url}]}]}

  - label: Links
    name: links
    folder: content/links
    # Where images are saved
    media_folder: /static/img/uploads
    # Path of images that are saved in the markdown file. We just make it relative to static/img/uploads, and also make GatsbyFileSystem set base path to static/img/uploads so ImageSharp sees stuff relative to static/img/uploads
    public_folder: ../../static/img/uploads
    create: false
    slug: index
    path: '{{title}}'
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string}
      - label: Links
        name: links
        widget: list
        summary: '"{{fields.text}}" linking to: {{fields.url}}'
        fields: 
          - {label: Link text, name: text, widget: string}
          - {label: URL, name: url, widget: url}
            
          #- label: 'Link'
          #  name: 'link'
          #  widget: 'string'
          #  pattern:
          #    - '((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)'
          #    - 'Enter a valid url'
          - label: Link Thumbnail
            name: thumbnail
            widget: croppedImage
            allow_multiple: false
            required: false
            image_width: 200px
            image_height: 150px
            object_fit: contain
            image_background: '#292f39'
            hint: The image is resized to 200x150, UNLESS the image is an SVG file. If the image is an SVG, no processing is done.